### ISSUE TITLE
Custom notifier (alert)

### ISSUE THREAD

**Issue by MakeHoney** [paldal-valley/client#17]
* 플랫폼에 notify module 추가한 뒤 플랫폼 모든 alert에 적용하기

**Comment by MakeHoney** [comment]
* vue-notification 패키지 설치 후 플러그인 등록했는데 앱에서 동작하지 않네요. . .?

**Comment by chiheon** [comment]
...?! 오오잉

**Comment by MakeHoney** [comment]
일단은 그냥 alert로 대체했습니드...
